### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by zyannick** [hezw2016/CDN_MRF#1]
Hello
Can you upload your code please?

**Comment by hezw2016** [comment]
sure, of course.
However, since I am now in United States as a visting schorlar, It is not so convenient for me to access the code, which is stored in the server in China. I will upload my testing code ASAP (within a week). 

Sorry to bother you, I forgot to update the Github page.

Best wishes

Zewei

2018-10-05 


He.Zewei 
Ph.D student
Institute of Advanced Manufacturing Engineering,
School of Mechanical Engineering,
Zhejiang University,
38 Zheda Road,Hangzhou, Zhejiang, P.R. China, 310027
Tel: (+86)17816856742(mobile)
Email:zeweihe@gmail.com/woshezewei@126.com /zeweihe@zju.edu.cn



发件人：Yannick Zoetgnande <notifications@github.com>
发送时间：2018-10-05 12:58
主题：[hezw2016/CDN_MRF] Code (#1)
收件人："hezw2016/CDN_MRF"<CDN_MRF@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hello
Can you upload your code please?
